### ISSUE TITLE
Генерация месяца и года действия карты

### ISSUE THREAD

**Issue by Katya6568** [Katya6568/DiplomaProject#1]
Запуталась с генерацией данных на (не)валидный месяц. Понятно, что валидные данные
будут в диапазоне (0;текущий месяц],а не валидные - (текущий месяц;12].
Но всё это верно только при то, что мы имеем ввиду только текущий год.
Например, сегодня мы заполняем поля с картой до 11-го месяца 2024 года. Тогда любой
месяц у нас будет валидный, получается. Я не понимаю, как установить зависимость
данных двух разных полей и генераторов. Можете с этим помочь?

src/test/java/data/DataGenerator.java

**Comment by Vladanna** [comment]
Создавайте пару невалидных карт
например вот так
` Calendar calendar = Calendar.getInstance();
        calendar.setTime(new Date());
        calendar.add(Calendar.MONTH, months);
        String date =  new SimpleDateFormat("dd.MM.yy").format(calendar.getTime());
        System.out.println(date);
        String month = new SimpleDateFormat("MM").format(calendar.getTime());
        String year = new SimpleDateFormat("yy").format(calendar.getTime());
        System.out.println(month + " " + year);
        return new Card("4444 4444 4444 4441", month, year, "Card Holder", "123");`
