### ISSUE TITLE
Поиск по селекторам на страницах оплат

### ISSUE THREAD

**Issue by Katya6568** [Katya6568/DiplomaProject#2]
Я очень не люблю индексы в селекторах, но я голову сломала,
как еще обозначить элементы. Как только я не пробовала, но в тестах он видит их только
с индексами. Можете дать наводку? 
И с таким поиском(по индексам) у меня не получается идентифицировать input__sub
с нужным полем, где должна быть ошибка.

src/test/java/pages/PaymentPage.java

**Comment by Vladanna** [comment]
про невальдное например вот ак
`$(".input__sub")`
про поиск - добавляйте хедеры, поля с текстом и только потом инпуты - используете хождение по дереву, так будет лучше
